### ISSUE TITLE
"Cant install the package"

### ISSUE THREAD

**Issue by CoolCat467** [CoolCat467/fix-lwjgl#30]
Originally posted https://github.com/CoolCat467/fix-lwjgl/discussions/29 by @Lolmc0587 and re-created as an issue

> Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/CoolCat467/fix-lwjgl.git
Cloning https://github.com/CoolCat467/fix-lwjgl.git to /tmp/pip-req-build-0dp_elgm
Running command git clone --filter=blob:none --quiet https://github.com/CoolCat467/fix-lwjgl.git /tmp/pip-req-build-0dp_elgm
Resolved https://github.com/CoolCat467/fix-lwjgl.git to commit https://github.com/CoolCat467/fix-lwjgl/commit/062266190fd3f0b63587178755759ab9d5861055
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
Building wheel for UNKNOWN (pyproject.toml) ... done
Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1793 sha256=11c1f2b1422a2a00762f74a53bc0d3c7170f897bf8cec28d634a8a0b9dd07f04
Stored in directory: /tmp/pip-ephem-wheel-cache-16g6_nzy/wheels/4f/4a/20/40e3de3311fe0daf2616bfa03058b9a4be607c10eaa19b3370
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0

**Comment by CoolCat467** [comment]
More likely than not, your pip installation is out of date, but I would need more information to be more sure. You can attempt to fix this by running
```console
pip install --upgrade pip
```
and then re-running the installation script.

**Comment by CoolCat467** [comment]
Originally posted by @Lolmc0587 https://github.com/CoolCat467/fix-lwjgl/discussions/29#discussioncomment-8816092

> i have found problem because i use pip 22.0.2 to install
now i upgrade to pip 24.0 and it work now
but now there are new error:
[log_launcher.txt](https://github.com/CoolCat467/fix-lwjgl/files/14626256/log_launcher.txt)
my setting:
https://private-user-images.githubusercontent.com/59377673/313446582-042d5168-b50b-4260-b3f5-9a5b1a0f9cba.png

**Comment by CoolCat467** [comment]
I would suggest updating ATLauncher and restarting it

**Comment by Lolmc0587** [comment]
`[17/03/2024 12:26:41 PM] Organising filesystem
[17/03/2024 12:26:41 PM] ATLauncher Version: 3.4.35.9 [1a4c0516cf5535166297e88e3239c78086db8589]
[17/03/2024 12:26:41 PM] App Arguments: ["--working-dir=.var/app/com.atlauncher.ATLauncher/data/","--no-launcher-update"]
[17/03/2024 12:26:41 PM] JVM Arguments: ["-Dawt.useSystemAAFontSettings=on","-Dswing.aatext=true"]
[17/03/2024 12:26:41 PM] Java Version: Java 17 (17.0.9)
[17/03/2024 12:26:41 PM] Java Path: /app/jre
[17/03/2024 12:26:41 PM] 64 Bit Java: true
[17/03/2024 12:26:41 PM] RAM Available: 15966MB
[17/03/2024 12:26:41 PM] Launcher Directory: .var/app/com.atlauncher.ATLauncher/data
[17/03/2024 12:26:41 PM] Arm: 64
[17/03/2024 12:26:41 PM] Using Flatpak!
[17/03/2024 12:26:41 PM] GPU: unknown (unknown) unknown 0MB VRAM
[17/03/2024 12:26:41 PM] CPU:  8 cores/8 threads
[17/03/2024 12:26:41 PM] Operating System: Freedesktop SDK (23.08 (Flatpak runtime) build 5.10.160-rockchip)
[17/03/2024 12:26:41 PM] Bitness: 64
[17/03/2024 12:26:41 PM] Uptime: 240
[17/03/2024 12:26:41 PM] Manufacturer: GNU/Linux
[17/03/2024 12:26:41 PM] Showing splash screen and loading everything
[17/03/2024 12:26:41 PM] Checking for updated files!
[17/03/2024 12:26:42 PM] Launcher finished loading everything
[17/03/2024 12:26:42 PM] Launcher opening
[17/03/2024 12:26:42 PM] Made By Bob*
[17/03/2024 12:26:42 PM] *(Not Actually)
[17/03/2024 12:26:42 PM] Setting up Bottom Bar
[17/03/2024 12:26:42 PM] Finished Setting up Bottom Bar
[17/03/2024 12:26:42 PM] Setting up Tabs
[17/03/2024 12:26:43 PM] Finished Setting up Tabs
[17/03/2024 12:26:43 PM] Showing Launcher
[17/03/2024 12:27:24 PM] Checking for updated files!
[17/03/2024 12:27:25 PM] Checking for updated files!`
i'm already at the newest version

**Comment by CoolCat467** [comment]
Not completely sure, but just saw `Using Flatpak!` in the logs there, and I think flatpaks do some special sandboxing stuff to try to be more secure? Because of this I would suggest re-installing ATLauncher as the java application version, but I think there might be an easier fix. In ATLauncher's Settings > General, close the the bottom there should be a checkbox for `Enable ARM Support` that was added [after I helped ATLauncher](https://github.com/ATLauncher/ATLauncher/issues/576#issuecomment-1200579521).

**Comment by CoolCat467** [comment]
Problem is, I can't seem to see that checkbox myself when I went looking for it to post a screenshot here, so if required you can go to your installation location of ATLauncher and find `configs/ATLauncher.json` and add
```
  "enableArmSupport": true,
```
on a new line somewhere inside the brackets. Make sure to close ATLauncher before editing this file.

**Comment by Lolmc0587** [comment]
> Problem is, I can't seem to see that checkbox myself when I went looking for it to post a screenshot here, so if required you can go to your installation location of ATLauncher and find `configs/ATLauncher.json` and add
> 
> ```
>   "enableArmSupport": true,
> ```
> 
> on a new line somewhere inside the brackets. Make sure to close ATLauncher before editing this file.

i see in the config already enable
i have switch to java version and still get that error

**Comment by Lolmc0587** [comment]
i'm not using a raspberry pi

**Comment by CoolCat467** [comment]
Could you post the logs of what happens if you don't have the wrapper enabled?

**Comment by Lolmc0587** [comment]
sure
https://paste.atlauncher.com/view/9c6d6ccc-ed51-428d-ac30-f15dae7cd620

**Comment by CoolCat467** [comment]
Try adding
```console
export MESA_GL_VERSION_OVERRIDE=4.3
```
as a pre-launch command. I've seen this fix it sometimes. If 4.3 doesn't work, try changing to `4.2COMPAT` and `4.5`,

**Comment by CoolCat467** [comment]
If that doesn't work,

**Comment by CoolCat467** [comment]
If that doesn't work, go to Java/Minecraft > Java Parameters and add `-Dorg.lwjgl.util.Debug=true` on to the end and post logs with that change.

**Comment by Lolmc0587** [comment]
> Try adding
> 
> ```
> export MESA_GL_VERSION_OVERRIDE=4.3
> ```
> 
> as a pre-launch command. I've seen this fix it sometimes. If `4.3` doesn't work, try changing to `4.2COMPAT` or `4.5`,

this working well
thanks for your help

**Comment by CoolCat467** [comment]
You are welcome! I'm glad I was able to help!
