### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Lolmc0587** [CoolCat467/fix-lwjgl#42]
**Describe the bug**

**Crash Log(s)**
[log_.txt](https://github.com/user-attachments/files/15756186/log_.txt)

**Screenshots**

**System Info (please complete the following information):**
 - OS: Linux
 - Architecture: arm64
 - Linux Flavor (if on Linux): ubuntu 24.04 LTS

**Minecraft Info (please complete the following information):**
 - Java Version: OpenJDK 21
 - Minecraft Version: 1.16.1
 - fix-lwjgl Version: Fix-LWJGL v1.3.1

**Additional context**
It crash in this version of minecraft

**Comment by CoolCat467** [comment]
[Searching the java issue](https://duckduckgo.com/?q=java.lang.NoSuchFieldException%253A+ucp), I am seeing a lot of results of people saying they had similar issues after updating to new java versions. Try installing java 8 and re-run?
Two ways to do this with ATLauncher. In your "Instances" tab, on the instance you want to run, click the "Settings" button.

1. First, easiest might still cause you problems, is use Mojang's verison of java 8 they supply: ![use_java_minecraft](https://github.com/CoolCat467/fix-lwjgl/assets/52022020/a5365b01-dfe2-41a2-8856-f8aafa995313)
2. Second and much better way, you install java 8 using your system package manager, restart ATLauncher, and then in same settings are you change the option to system java 8. (In this image from my laptop it's running amd java 8, but the same idea applies to things like the Orange Pi 5)
```
sudo apt update
sudo apt install openjdk-8-jdk
```
Restart ATLauncher, and then change the option to system java 8
 ![use_java_8](https://github.com/CoolCat467/fix-lwjgl/assets/52022020/665d7d31-4bdd-4952-a307-7a4cbb8e2bdf)

**Comment by Lolmc0587** [comment]
Yeah that's Java issue. Thanks for your support!
